# Generated by Django 3.0.5 on 2021-03-22 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0002_auto_20210322_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_order',
            name='Parts_Sub_Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CCC.parts_subcategory'),
            preserve_default=False,
        ),
    ]
