# Generated by Django 3.0.5 on 2021-03-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0003_auto_20210322_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_order',
            name='Parts_Sub_Category',
        ),
    ]
