# Generated by Django 3.0.5 on 2021-02-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0006_auto_20210223_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='superuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=7)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
