# Generated by Django 3.0.5 on 2021-02-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0007_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
