# Generated by Django 3.0.5 on 2021-03-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0008_auto_20210226_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='cus_request',
            name='orderid',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
