# Generated by Django 3.0.5 on 2021-03-04 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0010_remove_cus_request_orderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='parts_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='parts_subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('fit_model', models.CharField(max_length=50)),
                ('Parts_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CCC.parts_category')),
            ],
        ),
    ]
