# Generated by Django 3.0.5 on 2021-03-05 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0011_parts_category_parts_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('net_total', models.IntegerField()),
                ('Parts_Sub_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CCC.parts_subcategory')),
            ],
        ),
    ]
