# Generated by Django 3.0.5 on 2021-03-25 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0012_auto_20210325_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_order',
            name='Parts_Sub_Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CCC.parts_subcategory'),
        ),
    ]
