# Generated by Django 3.0.5 on 2021-03-05 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0012_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_cart',
            name='Customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CCC.customer'),
            preserve_default=False,
        ),
    ]
