# Generated by Django 3.0.5 on 2021-03-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0013_auto_20210325_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_order',
            old_name='products',
            new_name='parts',
        ),
    ]
