# Generated by Django 3.0.5 on 2021-03-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0013_order_cart_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_cart',
            name='net_total',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='subtotal',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='total',
            field=models.IntegerField(blank=True),
        ),
    ]
