# Generated by Django 3.0.5 on 2021-03-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0014_auto_20210325_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
