# Generated by Django 3.0.5 on 2021-03-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0014_auto_20210305_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_cart',
            name='net_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='subtotal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order_cart',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
