# Generated by Django 3.0.5 on 2021-03-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0017_order_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='parts_subcategory',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
