# Generated by Django 3.0.5 on 2021-03-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0019_auto_20210310_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_cart',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parts_subcategory',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
