# Generated by Django 3.0.5 on 2021-03-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0020_auto_20210311_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parts_subcategory',
            name='quantity',
        ),
    ]
