# Generated by Django 3.0.5 on 2021-03-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0021_remove_parts_subcategory_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_cart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order_cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order_cart',
            name='total',
        ),
        migrations.AddField(
            model_name='order_cart',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_cart',
            name='pro_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_cart',
            name='pro_qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order_cart',
            name='sub_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
