# Generated by Django 3.0.5 on 2021-03-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0022_auto_20210312_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_cart',
            old_name='pro_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='order_cart',
            old_name='pro_qty',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='order_cart',
            old_name='sub_total',
            new_name='total',
        ),
    ]
