# Generated by Django 3.0.5 on 2021-03-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0024_costomer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='costomer_order',
            name='mobile',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
