# Generated by Django 3.0.5 on 2021-03-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0025_costomer_order_mobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='costomer_order',
            new_name='customer_order',
        ),
    ]
